### PR TITLE
Fix team page - populate with current members

### LINKED ISSUE #183: 🐛 Bug: Current Members Page
### Reproduction Steps

The https://www.creativelabsucla.com/team screen is not displaying any of our members.

### Suggestions

Investigate the problem. To display members, we use Contentful (the CL login can be found on https://www.notion.so/clabs/978a0838aca0457691c46fcac80b5c0f?v=d6842114f8ef4085a13db22611548f0c). If you don't have access to that, contact Sunny or Travis. This members page pulls data from Contentful.

--- 

This is a :bug: Bug Report

### PR DESCRIPTION
**Pull request by bryanzhang3**
## Summary
- Imported 32 current members from Notion to Contentful
- Organized team page by team sections with headers
- Fixed director display logic

## Changes
- Added Contentful migration scripts
- Reorganized team page UI to group members by teams
- Added default avatar for all members

Fixes #183

### CODE REVIEW

File: src/app/team/TeamContent/TeamContent.tsx [hunk 1]
```diff
@@ -122,54 +146,34 @@ export default function TeamContent({ members, alumni }: { members: Array<any>,
...
-              menuButtonHoverColor="bg-blue-100"
-              options={["All Roles", "President", "Director", "Design", "Marketing/External", "Projects", "Finance", "Tech"]}
-              setValue={setAlumniRole}
-            />
-          </div>
-        </div>
-        <div className="p-12 grid gap-12 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 md:gap-8 lg:gap-12 xl:gap-16">
-          { alumniList?.filter((data) => data.enabled).map((data, idx) => 
-            {
-              const alumniData = data.fields;
```
Comment (tr-vs) [inline src/app/team/TeamContent/TeamContent.tsx:166]: It seems like the alumni section is wiped? I don't see it in the preview either--how hard is it to add the section back using the same contentful logic?

File: scripts/cleanup-test.js
Comment (tr-vs) [inline scripts/cleanup-test.js:1]: Not sure if we need to commit these scripts since migration should be a one time thing--feel free to correct me if I'm wrong

File: src/app/team/TeamContent/TeamContent.tsx [hunk 2]
```diff
@@ -1,12 +1,12 @@
...
 import DropdownMenu from "@/components/DropdownMenu";
 import ToolTip from "@/components/ToolTip";
-import Image from "next/image";
-import { useEffect, useState } from "react";
+import { useState } from "react";
 
 function MemberCard({ memberData, alumni, className } : { memberData: any, alumni: boolean, className?: string }) {
   const { name, year, titles, degree, fact, company, website} = memberData;
-  const photoURL = memberData?.photo?.fields?.file?.url;
+  // Use default avatar for all members (professional headshots coming soon)
```
Comment (tr-vs) [inline src/app/team/TeamContent/TeamContent.tsx]: Is the reason why we aren't using the images in contentful because some people have a picture set and some don't?

**Review by tr-vs — COMMENTED** [review]
Looks good! Went beyond what I expected! I left some comments, please review them! o7

File: src/app/team/TeamContent/TeamContent.tsx (hunk 2 above)
Comment (bryanzhang3) [reply src/app/team/TeamContent/TeamContent.tsx]: Yes, especially new members. Also I don't know if people know what photo they have in contentful so we should probably ask for them to send us a photo of what they want on the website. But yeah we can pull image from contentful once that's all set up.

File: src/app/team/TeamContent/TeamContent.tsx (hunk 1 above)
Comment (bryanzhang3) [reply src/app/team/TeamContent/TeamContent.tsx:166]: Yeah that's my fault I removed it because we don't have reliable alumni data yet but Kate and Angelina are working on it. I added it back so because it's probably more convenient to have it there and just update when we have proper alumni data. It will show incomplete alumni data currently though.

File: scripts/cleanup-test.js
Comment (bryanzhang3) [reply scripts/cleanup-test.js:1]: I think it may need to be run each year with the csv of the new members on notion. I also just updated publish-members.js to publish only people in the CSV. But if it's too much clutter we could store it somewhere else. I'm not too sure what do you think?

Comment (tr-vs) [reply scripts/cleanup-test.js:1]: Contentful should be a temporary solution (as we implement the membership portal, it will pull from Supabase instead), so these scripts don't need to be ran yearly

File: src/app/team/TeamContent/TeamContent.tsx (hunk 2 above)
Comment (tr-vs) [reply src/app/team/TeamContent/TeamContent.tsx]: Got it, can we make it so that we use the image in contentful, else use the default?

Comment (bryanzhang3) [reply src/app/team/TeamContent/TeamContent.tsx]: Done

File: scripts/cleanup-test.js
Comment (bryanzhang3) [reply scripts/cleanup-test.js:1]: I forgot about that, I removed the scripts

**Comment by tr-vs** [comment]
beautiful!
